//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archmage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Archmage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Charisma&quot;,
        ///  &quot;1&quot;: {
        ///
        ///  },
        ///  &quot;2&quot;: {
        ///
        ///  },
        ///  &quot;3&quot;: {
        ///
        ///  },
        ///  &quot;4&quot;: {
        ///
        ///  },
        ///  &quot;5&quot;: {
        ///
        ///  },
        ///  &quot;6&quot;: {
        ///
        ///  },
        ///  &quot;7&quot;: {
        ///
        ///  },
        ///  &quot;8&quot;: {
        ///
        ///  },
        ///  &quot;9&quot;: {
        ///
        ///  },
        ///  &quot;10&quot;: {
        ///
        ///  },
        ///  &quot;11&quot;: {
        ///
        ///  },
        ///  &quot;12&quot;: {
        ///
        ///  },
        ///  &quot;13&quot;: {
        ///
        ///  },
        ///  &quot;14&quot;: {
        ///
        ///  },
        ///  &quot;15&quot;: {
        ///
        ///  },
        ///  &quot;16&quot;: {
        ///
        ///  },
        ///  &quot;17&quot;: {
        ///
        ///  },
        ///  &quot;18&quot;: {
        ///
        ///  },
        ///  &quot;19&quot;: {
        ///
        ///  },
        ///  &quot;20&quot;: {
        ///
        ///  },
        ///  &quot;21&quot;: {
        ///
        ///  },
        ///  &quot;22&quot;: {
        ///
        ///  },
        ///  &quot;23&quot;: {
        ///
        ///  },
        ///  &quot;24&quot;: {
        ///
        ///  },
        ///  &quot;25&quot;: {
        ///
        ///  }
        ///}.
        /// </summary>
        internal static string Charisma {
            get {
                return ResourceManager.GetString("Charisma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Constitution&quot;,
        ///  &quot;1&quot;: {
        ///
        ///  },
        ///  &quot;2&quot;: {
        ///
        ///  },
        ///  &quot;3&quot;: {
        ///
        ///  },
        ///  &quot;4&quot;: {
        ///
        ///  },
        ///  &quot;5&quot;: {
        ///
        ///  },
        ///  &quot;6&quot;: {
        ///
        ///  },
        ///  &quot;7&quot;: {
        ///
        ///  },
        ///  &quot;8&quot;: {
        ///
        ///  },
        ///  &quot;9&quot;: {
        ///
        ///  },
        ///  &quot;10&quot;: {
        ///
        ///  },
        ///  &quot;11&quot;: {
        ///
        ///  },
        ///  &quot;12&quot;: {
        ///
        ///  },
        ///  &quot;13&quot;: {
        ///
        ///  },
        ///  &quot;14&quot;: {
        ///
        ///  },
        ///  &quot;15&quot;: {
        ///
        ///  },
        ///  &quot;16&quot;: {
        ///
        ///  },
        ///  &quot;17&quot;: {
        ///
        ///  },
        ///  &quot;18&quot;: {
        ///
        ///  },
        ///  &quot;19&quot;: {
        ///
        ///  },
        ///  &quot;20&quot;: {
        ///
        ///  },
        ///  &quot;21&quot;: {
        ///
        ///  },
        ///  &quot;22&quot;: {
        ///
        ///  },
        ///  &quot;23&quot;: {
        ///
        ///  },
        ///  &quot;24&quot;: {
        ///
        ///  },
        ///  &quot;25&quot;: {
        ///
        ///  }
        ///}.
        /// </summary>
        internal static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Dexterity&quot;,
        ///  &quot;1&quot;: {
        ///    &quot;ReactionAdjustment&quot;: -6,
        ///    &quot;MissileAttackAdjustment&quot;: -6, 
        ///    &quot;DefensiveAdjustment&quot;: 5
        ///  },
        ///  &quot;2&quot;: {
        ///    &quot;ReactionAdjustment&quot;: -4,
        ///    &quot;MissileAttackAdjustment&quot;: -4,
        ///    &quot;DefensiveAdjustment&quot;: 5
        ///  },
        ///  &quot;3&quot;: {
        ///    &quot;ReactionAdjustment&quot;: -3,
        ///    &quot;MissileAttackAdjustment&quot;: -3,
        ///    &quot;DefensiveAdjustment&quot;: 4
        ///  },
        ///  &quot;4&quot;: {
        ///    &quot;ReactionAdjustment&quot;: -2,
        ///    &quot;MissileAttackAdjustment&quot;: -2,
        ///    &quot;DefensiveAdjustment&quot;: 3
        ///  },
        ///  &quot;5&quot;: {
        ///    &quot;ReactionA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Dexterity {
            get {
                return ResourceManager.GetString("Dexterity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Intelligence&quot;,
        ///  &quot;1&quot;: {
        ///
        ///  },
        ///  &quot;2&quot;: {
        ///
        ///  },
        ///  &quot;3&quot;: {
        ///
        ///  },
        ///  &quot;4&quot;: {
        ///
        ///  },
        ///  &quot;5&quot;: {
        ///
        ///  },
        ///  &quot;6&quot;: {
        ///
        ///  },
        ///  &quot;7&quot;: {
        ///
        ///  },
        ///  &quot;8&quot;: {
        ///
        ///  },
        ///  &quot;9&quot;: {
        ///
        ///  },
        ///  &quot;10&quot;: {
        ///
        ///  },
        ///  &quot;11&quot;: {
        ///
        ///  },
        ///  &quot;12&quot;: {
        ///
        ///  },
        ///  &quot;13&quot;: {
        ///
        ///  },
        ///  &quot;14&quot;: {
        ///
        ///  },
        ///  &quot;15&quot;: {
        ///
        ///  },
        ///  &quot;16&quot;: {
        ///
        ///  },
        ///  &quot;17&quot;: {
        ///
        ///  },
        ///  &quot;18&quot;: {
        ///
        ///  },
        ///  &quot;19&quot;: {
        ///
        ///  },
        ///  &quot;20&quot;: {
        ///
        ///  },
        ///  &quot;21&quot;: {
        ///
        ///  },
        ///  &quot;22&quot;: {
        ///
        ///  },
        ///  &quot;23&quot;: {
        ///
        ///  },
        ///  &quot;24&quot;: {
        ///
        ///  },
        ///  &quot;25&quot;: {
        ///
        ///  },
        ///  &quot;Modif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Intelligence {
            get {
                return ResourceManager.GetString("Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Strength&quot;,
        ///  &quot;1&quot;: {
        ///
        ///  },
        ///  &quot;2&quot;: {
        ///
        ///  },
        ///  &quot;3&quot;: {
        ///
        ///  },
        ///  &quot;4&quot;: {
        ///
        ///  },
        ///  &quot;5&quot;: {
        ///
        ///  },
        ///  &quot;6&quot;: {
        ///
        ///  },
        ///  &quot;7&quot;: {
        ///
        ///  },
        ///  &quot;8&quot;: {
        ///
        ///  },
        ///  &quot;9&quot;: {
        ///
        ///  },
        ///  &quot;10&quot;: {
        ///
        ///  },
        ///  &quot;11&quot;: {
        ///
        ///  },
        ///  &quot;12&quot;: {
        ///
        ///  },
        ///  &quot;13&quot;: {
        ///
        ///  },
        ///  &quot;14&quot;: {
        ///
        ///  },
        ///  &quot;15&quot;: {
        ///
        ///  },
        ///  &quot;16&quot;: {
        ///
        ///  },
        ///  &quot;17&quot;: {
        ///
        ///  },
        ///  &quot;18&quot;: {
        ///
        ///  },
        ///  &quot;19&quot;: {
        ///
        ///  },
        ///  &quot;20&quot;: {
        ///
        ///  },
        ///  &quot;21&quot;: {
        ///
        ///  },
        ///  &quot;22&quot;: {
        ///
        ///  },
        ///  &quot;23&quot;: {
        ///
        ///  },
        ///  &quot;24&quot;: {
        ///
        ///  },
        ///  &quot;25&quot;: {
        ///
        ///  }
        ///}.
        /// </summary>
        internal static string Strength {
            get {
                return ResourceManager.GetString("Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;AbilityScore&quot;: &quot;Wisdom&quot;,
        ///  &quot;1&quot;: {
        ///
        ///  },
        ///  &quot;2&quot;: {
        ///
        ///  },
        ///  &quot;3&quot;: {
        ///
        ///  },
        ///  &quot;4&quot;: {
        ///
        ///  },
        ///  &quot;5&quot;: {
        ///
        ///  },
        ///  &quot;6&quot;: {
        ///
        ///  },
        ///  &quot;7&quot;: {
        ///
        ///  },
        ///  &quot;8&quot;: {
        ///
        ///  },
        ///  &quot;9&quot;: {
        ///
        ///  },
        ///  &quot;10&quot;: {
        ///
        ///  },
        ///  &quot;11&quot;: {
        ///
        ///  },
        ///  &quot;12&quot;: {
        ///
        ///  },
        ///  &quot;13&quot;: {
        ///
        ///  },
        ///  &quot;14&quot;: {
        ///
        ///  },
        ///  &quot;15&quot;: {
        ///
        ///  },
        ///  &quot;16&quot;: {
        ///
        ///  },
        ///  &quot;17&quot;: {
        ///
        ///  },
        ///  &quot;18&quot;: {
        ///
        ///  },
        ///  &quot;19&quot;: {
        ///
        ///  },
        ///  &quot;20&quot;: {
        ///
        ///  },
        ///  &quot;21&quot;: {
        ///
        ///  },
        ///  &quot;22&quot;: {
        ///
        ///  },
        ///  &quot;23&quot;: {
        ///
        ///  },
        ///  &quot;24&quot;: {
        ///
        ///  },
        ///  &quot;25&quot;: {
        ///
        ///  }
        ///}.
        /// </summary>
        internal static string Wisdom {
            get {
                return ResourceManager.GetString("Wisdom", resourceCulture);
            }
        }
    }
}
